### ISSUE TITLE
MobileVLM weights?

### ISSUE THREAD

**Issue by pHaeusler** [Meituan-AutoML/MobileVLM#1]
Awesome work!

Do you plan on releasing the weights for MobileVLM?

**Comment by cxxgtxy** [comment]
Yes. We have updated  weights of MobileLLaMA.

**Comment by Foul-Tarnished** [comment]
Is there any android app that uses this ?
[Sherpa](https://github.com/dsd/sherpa) (llama2 7b) run slowly, and even crash with long context on my 12gb (+4gb swap) on SD865 ...

**Comment by huyiming2018** [comment]
> Is there any android app that uses this ? [Sherpa](https://github.com/dsd/sherpa) (llama2 7b) run slowly, and even crash with input/long context with 12gb (+4gb swap) on SD865 ...
> 
> Edit : Apparently there's this more updated fork of Sherpa https://github.com/Mobile-Artificial-Intelligence/maid/

Based on our experience, it is normal for the 7B model to have slow inference on mobile devices. We suggest reducing the model size or using higher specification equipment.
