### ISSUE TITLE
Question about mobile platform deploy 

### ISSUE THREAD

**Issue by JiaoYanMoGu** [Meituan-AutoML/MobileVLM#10]
As mentioned in other issues:
- https://github.com/Meituan-AutoML/MobileVLM/issues/8
- https://github.com/Meituan-AutoML/MobileVLM/issues/4

Deploying on mobile platform such as Snapdragon 888 is based on llama.cpp, the questions  I want to ask is:
- Did you use QNN to deploy the model?
- Did you rewrite the gpu kernel based on opencl or use clblast?

**Comment by er-muyue** [comment]
Hi, we are closing this issue due to the inactivity. Hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!
