### ISSUE TITLE
Is it possible to provide pretrained mm_projector.bin

### ISSUE THREAD

**Issue by KP-Zhang** [Meituan-AutoML/MobileVLM#19]
Thank you for your excellent work; the quality is truly impressive. 
Due to our limited computational resources, we are unable to pretrain the **MobileVLM-1.7B** model. As a result, we are considering the option of finetuning with Lora, bypassing the pretraining phase. Would it be possible for you to supply the pretrained **mm_projector.bin**? We intend to use it as follows:
--pretrain_mm_mlp_adapter ${OUTPUT_DIR_PT}/mm_projector.bin

**Comment by er-muyue** [comment]
Sorry for the late reply. We have uploaded the stage1 projector weight of the MobileVLMv1-1.7B, please enjoy it [here](https://github.com/Meituan-AutoML/MobileVLM/releases/download/v0.2/mobilevlmv1_1.7b_stage1_mm_projector.bin).
