### ISSUE TITLE
inference on iPhone 

### ISSUE THREAD

**Issue by tstanek390** [Meituan-AutoML/MobileVLM#2]
Hello,
thanks for sharing these very promising LLMs. I'd like to run it on iOS, but as I'm a noob at coding and stuff, I don't really know how to start. I'm an healtcare professional and would love to give it a try. Any hints/tips ?
Thanks a lot and all the best to the new year!
Teodor

**Comment by huyiming2018** [comment]
Maybe you can refer to this example from lamma.cpp community: https://github.com/ggerganov/llama.cpp/discussions/4508

**Comment by tstanek390** [comment]
Thx, but I guess I would need GGUF version of the model to run it with LLama.cpp..?

**Comment by YangYang-DLUT** [comment]
You can convert the model to GGUF follow the instruction of [https://github.com/ggerganov/llama.cpp/tree/master/examples/llava](url). The detailed deployment instruction is in process and will be released soon.

**Comment by YangYang-DLUT** [comment]
We have updated [README.md](https://github.com/Meituan-AutoML/MobileVLM#-deployment-on-mobile-devices-) with the deployment instruction on Android devices with customized `llama.cpp`. Have a try!

The inference plan on iPhone is on schedule but not proposed yet. Any ideas?

**Comment by jasonw247** [comment]
Thanks for adding this! Are you planning on submitting a PR to llama.cpp, or keeping the forked repo?

**Comment by YangYang-DLUT** [comment]
We have submitted a [PR](https://github.com/ggerganov/llama.cpp/pull/4954) to `llama.cpp`. We want to get the support of open-source communities, since that there are a lot space for optimization of the deployment on mobile devices.

**Comment by er-muyue** [comment]
Hi, we are closing this issue due to the inactivity. Hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!
