### ISSUE TITLE
any lora for stage 2?

### ISSUE THREAD

**Issue by shawnricecake** [Meituan-AutoML/MobileVLM#22]
Hi,

can we use lora to finetune the llama part based on the pretrained weights of llama in stage 2?

Thanks

**Comment by er-muyue** [comment]
Within the scope of MobileVLM license, you are free to use our pretrained weights in your projects. In addition, we also provide the stage2 lora-fintune code script, please refer to [here](https://github.com/Meituan-AutoML/MobileVLM/blob/f540e17f05b63f0568de1c45d12317f29808ddf7/run.sh#L135).

**Comment by er-muyue** [comment]
Hi, hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!
