### ISSUE TITLE
Hugging Face demo

### ISSUE THREAD

**Issue by merveenoyan** [Meituan-AutoML/MobileVLM#24]
Hello 👋  Great work with MobileVLM! I was wondering if you'd like to build a demo and host it on HF Spaces (since you are already hosting checkpoints)

**Comment by cxxgtxy** [comment]
Thanks! Sure.

**Comment by merveenoyan** [comment]
@cxxgtxy great! if you need help or any questions I'd be very happy to help out 🤗
