### ISSUE TITLE
Repetitive response problem with VLM 

### ISSUE THREAD

**Issue by Muhammad4hmed** [Meituan-AutoML/MobileVLM#27]
Hi, first of all thank you so much for this great contribution!

I've been testing your model on driving videos and I noticed a strange thing that some times it keeps repeating the output like in given image:
![Screenshot from 2024-02-20 23-11-00](https://github.com/Meituan-AutoML/MobileVLM/assets/46111472/d22f694e-a537-4941-8afd-57b56181d89e)
I think this might be a parameters issue, so the hyperparameters I'm using are:
```
{
      "model_path": 'mtgv/MobileVLM_V2-3B,
      "conv_mode": "v1",
      "temperature": 0.0, 
      "top_p": None,
      "num_beams": 1,
      "max_new_tokens": 512,
      "load_8bit": False,
      "load_4bit": False,
  }
```

can you please look into it and what might be the issue, also if possible, please do share optimal hyperparameters for `mtgv/MobileVLM_V2-3B,`.

Thanks

**Comment by YangYang-DLUT** [comment]
Could you provide the picture and the prompt? We try to reproduce this problem.

**Comment by YangYang-DLUT** [comment]
Does this problem happen while directly using our inference script?

**Comment by Muhammad4hmed** [comment]
Hi @YangYang-DLUT 

> Could you provide the picture and the prompt? We try to reproduce this problem.

I've already provided the response image in the issue, the text returned from the model is repetitive like this: 

```
Prompt: Is the driver driving safely or distracted?
Response:
1. The driver is not driving attentively.
2. The driver is not driving attentively.
3. The driver is not driving attentively.
4. The driver is not driving attentively.
5. The driver is not driving attentively.
....
```

Yes I'm using the same inference code provided with the hyper-parameters I provided in the issue.

> Does this problem happen while directly using our inference script?

Thanks

**Comment by YangYang-DLUT** [comment]
Could you attach the exact image file to the comment? 😸

**Comment by Muhammad4hmed** [comment]
sure, here it is
![Screenshot from 2024-02-20 23-11-00](https://github.com/Meituan-AutoML/MobileVLM/assets/46111472/e079a56c-9e19-454c-92c6-054d76671123)

**Comment by YangYang-DLUT** [comment]
![image](https://github.com/Meituan-AutoML/MobileVLM/assets/108061784/6fb959d0-f08c-4191-9b90-6d7350a07614)
I am looking forward to get the original file of the input image on the left of the screen shot. 😸 Could you attach it to the comment?

**Comment by Muhammad4hmed** [comment]
Oh, sorry. Here it is:
![Screenshot from 2024-02-20 23-11-00](https://github.com/Meituan-AutoML/MobileVLM/assets/46111472/354c1137-8b45-4254-8c3b-52fc5548e97e)

**Comment by Muhammad4hmed** [comment]
By the way, to work with videos, I'm using image grid. so this is the input I used:

The exact prompt:
```
You are a driving assistant. You will help me during driving by providing details and answering my questions. Remember to keep the response accurate and do not repeat.

This image shows 4 consecutive video frames captured from a dashcam at 4-second intervals. 
Instead of general driving instructions, analyze the image carefully and provide specific, detailed bullet points for each action you would take as the driver in this situation. Remember, the red lines represent my vehicle's current lane and they are only added for your assistance, I can't see them.

USER: Is the driver driving attentively or distracted?
ASSISTANT: 
```

![grid](https://github.com/Meituan-AutoML/MobileVLM/assets/46111472/73760c11-a636-462f-80d5-b74c80c691d4)

**Comment by Muhammad4hmed** [comment]
Problem solved, with a few debugging, I found that I was missing "<image>" tag in the prompt which was causing this.

**Comment by weizhou1991** [comment]
> Problem solved, with a few debugging, I found that I was missing
> 
> ```
> <image>
> ```
> 
> tag in the prompt which was causing this.

Hi Sir, 
What's ur meaning by miss <image>tag ?

**Comment by Muhammad4hmed** [comment]
Hi,

Normally when directly running MobileVLM, you won't require this but if you
are building something which works directly with the model, you will need
to make sure to follow this format:

Prompt = """
USER: <image>
Question here

ASSISTANT: """

Thanks
