### ISSUE TITLE
Where can I obtain the data used for MobileVLM v2 training?

### ISSUE THREAD

**Issue by xushilin1** [Meituan-AutoML/MobileVLM#28]
Where can I obtain the data used for MobileVLM v2 training?

**Comment by rangmiao** [comment]
Where can I obtain MobileVLM V2 training data and code?

**Comment by er-muyue** [comment]
The training data and code of MobileVLM V2 have been released. Please refer to our latest [README](https://github.com/Meituan-AutoML/MobileVLM) and enjoy them.
