### ISSUE TITLE
mobilevlm_v2 with lora

### ISSUE THREAD

**Issue by rangmiao** [Meituan-AutoML/MobileVLM#30]
Dear author, I would like to inquire whether mobilevlm_v2 can be trained using the LoRa method for language models, and if so, how significant is the impact on accuracy?

**Comment by sxu1997** [comment]
Sure, under setting of mobilevlm v2 with increasing data samples, using LoRA drops 1-2 points on average performance compared with full parameter fintuning.

**Comment by er-muyue** [comment]
Hi, we are closing this issue due to the inactivity. Hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!
