### ISSUE TITLE
有中文的readme没有？两张rtx A4000跑不起来，报错

### ISSUE THREAD

**Issue by life2048** [Meituan-AutoML/MobileVLM#32]
使用readme上的vlm推理代码，运行最后保存，请问
参数上是否需要做一些调整
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)

**Comment by weifei7** [comment]
Please make sure your torch is the CUDA version. If it still not work, you could add `device_map='cuda'` to [here](https://github.com/Meituan-AutoML/MobileVLM/blob/main/scripts/inference.py#L19) -> `tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.load_8bit, args.load_4bit, device_map='cuda')`
