### ISSUE TITLE
请问推理支持batch跑吗？

### ISSUE THREAD

**Issue by LianghuiGuo** [Meituan-AutoML/MobileVLM#33]
![image](https://github.com/Meituan-AutoML/MobileVLM/assets/87937587/5a7e2a28-4189-47a7-a801-1f2f83535e2a)
可以支持input_ids， images_tensor是batch的形式吗，批量推理

**Comment by huyiming2018** [comment]
Sorry, our test code is run on a single batch. If you wish to perform batch inference, please refer to the official [Transformers tutorial](https://github.com/huggingface/transformers/issues/26061) and update the Transformers library to the specified version.
