### ISSUE TITLE
How  to use our own dataset to test?

### ISSUE THREAD

**Issue by QvQKing** [Meituan-AutoML/MobileVLM#34]

**Comment by weifei7** [comment]
Please refer to [LLaVA-v1.5 Evaluation Guideline](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md) to organize your own test dataset. 
Then start your test program refer to the test script we provided: 
add your script in [scripts/benchmark](https://github.com/Meituan-AutoML/MobileVLM/tree/main/scripts/benchmark), and start it in [scripts/benchmark.sh](https://github.com/Meituan-AutoML/MobileVLM/blob/main/scripts/benchmark.sh).

**Comment by er-muyue** [comment]
Hi, we are closing this issue due to the inactivity. Hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!
