### ISSUE TITLE
A100推理为啥很慢呢？是我Inference姿势不对吗？

### ISSUE THREAD

**Issue by LianghuiGuo** [Meituan-AutoML/MobileVLM#35]
<img width="493" alt="image" src="https://github.com/Meituan-AutoML/MobileVLM/assets/87937587/4f95f75c-fac9-4379-ad04-737393d1eff0">

单卡A100，一条数据inference time : 9.407606601715088

**Comment by huyiming2018** [comment]
How many output tokens are there currently for inference, and could you provide a speed metric in the style of how many tokens per second, as well as the GPU utilization situation?
