### ISSUE TITLE
请问支持量化推理吗？

### ISSUE THREAD

**Issue by LianghuiGuo** [Meituan-AutoML/MobileVLM#36]
可以指定load-8bit 或者 load-4bit吗？

**Comment by er-muyue** [comment]
Yes, please refer to [here](https://github.com/Meituan-AutoML/MobileVLM?tab=readme-ov-file#example-for-mobilevlmmobilevlm-v2-model-inference) and turn on the `load_8bit` or `load_4bit` for your purpose.
