### ISSUE TITLE
vision_tower读取不到内容，返回none

### ISSUE THREAD

**Issue by caramel678** [Meituan-AutoML/MobileVLM#5]
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
You are using a model of type llama to instantiate a model of type mobilevlm. This is not supported for all configurations of models and can yield errors.
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embedding dimension will be 32001. This might induce some performance reduction as *Tensor Cores* will not be available. For more details about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
Traceback (most recent call last):
  File "D:\MobileVLM-main\scripts\inference.py", line 67, in <module>
    inference_once(args)
  File "D:\MobileVLM-main\scripts\inference.py", line 19, in inference_once
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path)
  File "D:\MobileVLM-main\mobilevlm\model\mobilevlm.py", line 259, in load_pretrained_model
    if not vision_tower.is_loaded:
AttributeError: 'NoneType' object has no attribute 'is_loaded'

为什么vision_tower读取不到内容，返回none

**Comment by er-muyue** [comment]
Hi, please confirm whether the model corresponding to `args.model_path` has been modified? And does the path of 
 `mm_vision_tower` field in `args.model_path/config.json` correctly exist for the *clip-vit model*?

**Comment by er-muyue** [comment]
Hi, we are closing this issue due to the inactivity. Hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!

**Comment by Bobby-youngking** [comment]
i solved this issue. you can modify the run.sh，--model_name_or_path ${LANGUAGE_MODEL} \
