### ISSUE TITLE
how to use lora

### ISSUE THREAD

**Issue by liuweixue001** [Meituan-AutoML/MobileVLM#6]
Could you provide code for training and using LoRa?

thank you!

**Comment by sriramsowmithri9807** [comment]
`#include <RH_RF95.h>

#define RFM95_CS 10
#define RFM95_RST 9
#define RFM95_INT 2

RH_RF95 rf95(RFM95_CS, RFM95_INT);

void setup() {
  Serial.begin(9600);
  while (!Serial) ;
  
  if (!rf95.init()) {
    Serial.println("LoRa initialization failed!");
    while (1);
  }
  Serial.println("LoRa initialized!");

  if (!rf95.setFrequency(915.0)) {
    Serial.println("Frequency setting failed!");
    while (1);
  }
  Serial.println("Frequency set to 915 MHz");

  rf95.setTxPower(23, false); // Set transmission power to 23dBm
}

void loop() {
  const char *message = "Hello, LoRa!";
  rf95.send((uint8_t *)message, strlen(message));
  rf95.waitPacketSent();
  delay(2000);
}
`

**Comment by sriramsowmithri9807** [comment]
RECOVER CODE :

`
#include <RH_RF95.h>

#define RFM95_CS 10
#define RFM95_RST 9
#define RFM95_INT 2

RH_RF95 rf95(RFM95_CS, RFM95_INT);

void setup() {
  Serial.begin(9600);
  while (!Serial) ;

  if (!rf95.init()) {
    Serial.println("LoRa initialization failed!");
    while (1);
  }
  Serial.println("LoRa initialized!");

  if (!rf95.setFrequency(915.0)) {
    Serial.println("Frequency setting failed!");
    while (1);
  }
  Serial.println("Frequency set to 915 MHz");

  rf95.setTxPower(23, false); // Set transmission power to 23dBm

  Serial.println("Ready to receive...");
}

void loop() {
  if (rf95.available()) {
    uint8_t buf[RH_RF95_MAX_MESSAGE_LEN];
    uint8_t len = sizeof(buf);
    if (rf95.recv(buf, &len)) {
      buf[len] = 0;
      Serial.print("Received: ");
      Serial.println((char *)buf);
    }
  }
}
 FOR MORE INFORMATION 
sowmithrisriram7@gmail.com

**Comment by johnwick123f** [comment]
@sriramsowmithri9807 i believe they meant low rank adapter lora not the lora that is used for communication

**Comment by liuweixue001** [comment]
@sriramsowmithri9807 thanks，but what I want to ask is how to fine-tune a model using low rank method to adapt to my specific task,  just like @johnwick123f mentioned.

**Comment by sriramsowmithri9807** [comment]
ok! i will look atfer this

**Comment by cxxgtxy** [comment]
> Could you provide code for training and using LoRa?
> 
> thank you!

Yes. We are preparing these codes. It is scheduled to be released in the next week.

**Comment by cxxgtxy** [comment]
> Could you provide code for training and using LoRa?
> 
> thank you!

The lora code is released. Please check.  @liuweixue001 
Thanks!

**Comment by liuweixue001** [comment]
> > Could you provide code for training and using LoRa?
> > thank you!
> 
> The lora code is released. Please check. @liuweixue001 Thanks!

can you provide a mm_projector.bin file, i only have a 3090, pretrain is difficult.

**Comment by er-muyue** [comment]
> > > Could you provide code for training and using LoRa?
> > > thank you!
> > 
> > 
> > The lora code is released. Please check. @liuweixue001 Thanks!
> 
> can you provide a mm_projector.bin file, i only have a 3090, pretrain is difficult.

We have uploaded the stage1 projector weight of the MobileVLMv1-1.7B, please enjoy it [here](https://github.com/Meituan-AutoML/MobileVLM/releases/download/v0.2/mobilevlmv1_1.7b_stage1_mm_projector.bin)!
